### ISSUE TITLE
1001 test case fail

### ISSUE THREAD

**Issue by zhangweih** [JiaChenx/C--study#2]
input "1000000 1",  output "1000,001", but the correct result should be "1,000,001".

**Comment by zhangweih** [comment]
VERY VERY IMPORTANT: the boudary test case must BE CONSIDERED. For test 1001, boundary test case include (a=1000000 b=somevalue) or (a=-1000000 b=somevalue)

**Comment by JiaChenx** [comment]
> input "1000000 1", output "1000,001", but the correct result should be "1,000,001".

Version2.0 has solved the problem, thanks for suggestion.
